.TH grass-ogr 1 "" "GRASS 8.4.1" "GRASS GIS User's Manual"
.SH OGR DATABASE DRIVER
This driver is principally only used
by \fIv.external\fR.
.SH SEE ALSO
\fI
SQL support in GRASS GIS
\fR
.PP
\fI
v.external
\fR
.SH SOURCE CODE
.PP
Available at:
OGR DATABASE DRIVER source code
(history)
.PP
Latest change: Tuesday Dec 17 20:17:20 2024 in commit: d962e90c026708a4815ea2b9f46c0e84c17de22d
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2025
GRASS Development Team,
GRASS GIS 8.4.1 Reference Manual
