.TH helptext 1 "" "GRASS 8.4.1" "GRASS GIS User's Manual"
.SH GRASS GIS Quickstart
.PP
When launching GRASS GIS for the first time, you will open a
\fBdefault project\fR \(dqworld_latlog_wgs84\(dq where you can find a map layer
called \(dqcountry_boundaries\(dq showing a world map in the WGS84 coordinate system.
.br
.PP
The main component of the Data tab is the \fIData Catalog\fR
which shows the GRASS GIS hierarchical structure consisting of
database ,
project  and
mapset .
.IP " \fBGRASS database\fR (directory with projects)" 4m
.br
Running GRASS GIS for the first time, a folder named \(dqgrassdata\(dq is automatically
created. Depending on your operating system, you can find it in your $HOME
directory (*nix) or My Documents (MS Windows).
.IP " \fBproject\fR (previously called location)" 4m
.br
A project is defined by its coordinate reference system (CRS).
In the case of the default project, it is a geographic coordinate reference system
WGS84 (EPSG:4326). If you have data in another CRS than WGS84, you should create
a new project corresponding to your system.
.IP " \fBmapset\fR (a subproject)" 4m
.br
Each project can have many mapsets for managing different aspects of
a project or project\(cqs subregions. When creating a new project, GRASS GIS
automatically creates a special mapset called PERMANENT where the core
data for the project can be stored.
.PP
For more info about data hierarchy, see
GRASS GIS Database page.
.SH GRASS started in the default project, now what?
.PP
First, if you would like to get to know GRASS better before importing your own data,
please download provided samples such as the \(dqNorth Carolina\(dq dataset.
You can simply reach them through
\(dqDownload sample project to current database\(dq management icon
\&.
.PP
To work with your own data, you typically want to first create a new project
with a
coordinate reference system (CRS) suitable for your study area or one that
matches your data\(cqs CRS. The Project Wizard
will help you with that by guiding you through a series of dialogs to browse
and select predefined projections (also via EPSG code) or to define individual
projections.
.SS Creating a New project with the Project Wizard
.PP
If you know the CRS of your data or study area,
you can fill EPSG code
or description and Project Wizard finds appropriate CRS from a predefined list
of projections.
If you do not know CRS of you data, you can read it from your georeferenced
data file (e.g. shapefile or GeoTiff file with the related metadata properly
included).
.SS Importing data
After creating a new project, you are ready to import your data. You can use
simple raster or vector data import ,
or a variety of more specialized tools.
If the data\(cqs CRS does not match your project\(cqs CRS, data will be automatically reprojected.
After import your raster or vector data are added as a layer to Map Display.
To change layer properties, go to Display tab.
To analyze your data, search for a tool in the Modules tab.
.SH Text\-based startup and project creation
GRASS GIS can be run entirely without using the graphical user interface.
See examples of running GRASS GIS from a command line.
.SH See also
\fI
GRASS GIS Reference Manual
.br
GRASS GIS startup program manual page
.br
GRASS GIS tutorials and books
\fR
.PP
List of EPSG codes (Database of worldwide coordinate systems),
CRS Explorer \- PROJ codes, and
EPSG Geodetic Parameter Dataset
.SH SOURCE CODE
.PP
Available at:
GRASS GIS Quickstart source code
(history)
.PP
Latest change: Tuesday Jan 07 11:21:29 2025 in commit: f1f5dfa35dd86f1cc8cf5bfc7ee91d3d17b937c1
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2025
GRASS Development Team,
GRASS GIS 8.4.1 Reference Manual
