.TH i.band.library 1 "" "GRASS 8.4.1" "GRASS GIS User's Manual"
.SH NAME
\fI\fBi.band.library.py\fR\fR  \- Prints available semantic label information used for multispectral data.
.SH KEYWORDS
general, imagery, semantic label, image collections
.SH SYNOPSIS
\fBi.band.library.py\fR
.br
\fBi.band.library.py \-\-help\fR
.br
\fBi.band.library.py\fR [\-\fBe\fR]  [\fBpattern\fR=\fIstring\fR]   [\fBoperation\fR=\fIstring\fR]   [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-e\fR" 4m
.br
Print extended metadata information
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBpattern\fR=\fIstring\fR" 4m
.br
Semantic label search pattern (examples: L, S2, .*_2, S2_1)
.IP "\fBoperation\fR=\fIstring\fR" 4m
.br
Operation to be performed
.br
Options: \fIprint\fR
.br
Default: \fIprint\fR
.SH DESCRIPTION
\fIi.band.library\fR prints available band information of multispectral data
defined by GRASS GIS. The following multispectral sensors are supported
by default (other band reference registry files can be added, see below):
.PP
Generic multispectral system:
.RS 4n
.IP \(bu 4n
gen_r Visible red
.IP \(bu 4n
gen_g Visible green
.IP \(bu 4n
gen_b Visible blue
.IP \(bu 4n
gen_pan Visible panchromatic
.IP \(bu 4n
gen_nir Near infrared
.RE
.PP
Landsat\-5:
.RS 4n
.IP \(bu 4n
L5_1 Visible (Blue)
.IP \(bu 4n
L5_2 Visible (Green)
.IP \(bu 4n
L5_3 Visible (Red)
.IP \(bu 4n
L5_4 Near\-Infrared
.IP \(bu 4n
L5_5 Short\-wave infrared
.IP \(bu 4n
L5_6 Thermal
.IP \(bu 4n
L5_7 Short\-wave infrared
.RE
.PP
Landsat\-7:
.RS 4n
.IP \(bu 4n
L7_1 Visible (Blue)
.IP \(bu 4n
L7_2 Visible (Green)
.IP \(bu 4n
L7_3 Visible (Red)
.IP \(bu 4n
L7_4 Near\-Infrared
.IP \(bu 4n
L7_5 Near\-Infrared
.IP \(bu 4n
L7_6 Thermal
.IP \(bu 4n
L7_7 Mid\-Infrared
.IP \(bu 4n
L7_8 Panchromatic
.RE
.PP
Landsat\-8:
.RS 4n
.IP \(bu 4n
L8_1 Visible (Coastal/Aerosol)
.IP \(bu 4n
L8_2 Visible (Blue)
.IP \(bu 4n
L8_3 Visible (Green)
.IP \(bu 4n
L8_4 Visible (Red)
.IP \(bu 4n
L8_5 Near\-Infrared
.IP \(bu 4n
L8_6 SWIR 1
.IP \(bu 4n
L8_7 SWIR 2
.IP \(bu 4n
L8_8 Panchromatic
.IP \(bu 4n
L8_9 Cirrus
.IP \(bu 4n
L8_10 TIRS 1
.IP \(bu 4n
L8_11 TIRS 1
.RE
.PP
Sentinel\-2:
.RS 4n
.IP \(bu 4n
S2_1 Visible (Coastal/Aerosol)
.IP \(bu 4n
S2_2 Visible (Blue)
.IP \(bu 4n
S2_3 Visible (Green)
.IP \(bu 4n
S2_4 Visible (Red)
.IP \(bu 4n
S2_5 Vegetation Red Edge 1
.IP \(bu 4n
S2_6 Vegetation Red Edge 2
.IP \(bu 4n
S2_7 Vegetation Red Edge 3
.IP \(bu 4n
S2_8 Near\-Infrared
.IP \(bu 4n
S2_8A Narrow Near\-Infrared
.IP \(bu 4n
S2_9 Water vapour
.IP \(bu 4n
S2_10 SWIR \- Cirrus
.IP \(bu 4n
S2_11 SWIR 1
.IP \(bu 4n
S2_12 SWIR 2
.RE
.PP
Band references to be printed can be filtered by a search pattern (or
fully defined band reference identifier) which can be specified
by \fBpattern\fR option. For pattern syntax
see Python
regular expression operations documentation. By
default, \fIi.band.library\fR prints all available band references.
.PP
Extended metadata (central wavelength, spatial resolution, etc.) is printed
only when the \fB\-e\fR flag is given.
.SH Band reference and semantic label relation
.PP
Band references are a special case (a subset) of semantic labels.
Any string can be a semantic label but strings identifying specific
remote sensing platform bands (=band references)
can have additional metadata managed by \fIi.band.library\fR.
Specific band reference can be assigned to a raster map as a semantic
label by \fIr.semantic.label\fR
or \fIr.support\fR modules.
.SH NOTES
.PP
Semantic label concept is supported by temporal GRASS modules, see
\fIt.register\fR,
\fIt.rast.list\fR,
\fIt.info\fR
and \fIt.rast.mapcalc\fR
modules for examples.
.SS Image collections
Image collections are the common data type to reference time series of
multi band data. It is used in many frameworks
(see Google
Earth Engine API for example) to address multi spectral satellite
images series. GRASS supports a multi\-band raster layer approach
basically with the imagery group concept
(\fIi.group\fR). A new semantic label
concept is designed in order to support image collections in GRASS
GIS.
.SS Band reference registry files
Band reference information is stored in JSON files with a pre\-defined
internal data structure. A minimalistic example is shown below.
.br
.nf
\fC
{
    \(dqSentinel2\(dq: {
        \(dqdescription\(dq: \(dqThe Sentinel\-2 A/B bands\(dq,
        \(dqshortcut\(dq: \(dqS2\(dq,
        \(dqinstruments\(dq: \(dqMultiSpectral Instrument (MSI) optical and infrared\(dq,
        \(dqlaunched\(dq: \(dq23 June 2015 (A); 07 March 2017 (B)\(dq,
        \(dqsource\(dq: \(dqhttps://sentinel.esa.int/web/sentinel/missions/sentinel\-2\(dq,
        \(dqbands\(dq: {
            \(dq1\(dq: {
                \(dqSentinel 2A\(dq : {
                    \(dqcentral wavelength (nm)\(dq: 443.9,
                    \(dqbandwidth (nm)\(dq: 27
                },
                \(dqSentinel 2B\(dq : {
                    \(dqcentral wavelength (nm)\(dq: 442.3,
                    \(dqbandwidth (nm)\(dq: 45
                },
                \(dqspatial resolution (meters)\(dq: 60,
                \(dqtag\(dq: \(dqVisible (Coastal/Aerosol)\(dq
            },
            \(dq2\(dq: {
                \(dqSentinel 2A\(dq : {
                    \(dqcentral wavelength (nm)\(dq: 496.6,
                    \(dqbandwidth (nm)\(dq: 98
                },
                \(dqSentinel 2B\(dq : {
                    \(dqcentral wavelength (nm)\(dq: 492.1,
                    \(dqbandwidth (nm)\(dq: 98
                },
                \(dqspatial resolution (meters)\(dq: 10,
                \(dqtag\(dq: \(dqVisible (Blue)\(dq
            }
        }
    }
}
\fR
.fi
Each series starts with an unique identifier (\(dqSentinel2\(dq
in example above). Required attributes are only two:
a \fCshortcut\fR and \fCbands\fR. Note that a \fIshortcut\fR
must be unique in all band reference registry files. Number of other
attributes is not defined or even limited (in example above
only \fCdescription\fR and \fCinstruments\fR attributes are
defined). List of bands is defined by a \fCbands\fR attribute. Each
band is defined by an identifier (\(dq1\(dq, \(dq2\(dq in example above). List of
attributes describing each band is not pre\-defined or limited. In
example above each band is described by a \fCcentral wavelength
(nm)\fR, \fCbandwidth (nm)\fR, and a \fCtag\fR.
.PP
Band reference identifier defined by \fBpattern\fR option is given by
a \fIshortcut\fR in order to print band reference information for
whole series or by specific \fIshortcut\fR_\fIband\fR
identifier.
.PP
System\-defined registry files are located in GRASS GIS installation
directory (\fC$GISBASE/etc/i.band.library\fR). Note that
currently \fIi.band.library\fR allows managing only system\-defined registry
files. Support for user\-defined registry files is planned to be
implemented, see KNOWN ISSUES section for
details.
.SH EXAMPLES
.SS Print all available band references
.br
.nf
\fC
i.band.library
S2_1 Visible (Coastal/Aerosol)
S2_2 Visible (Blue)
\&...
L7_1 Visible (Blue)
L7_2 Visible (Green)
\&...
L8_1 Visible (Coastal/Aerosol)
L8_2 Visible (Blue)
\&...
\fR
.fi
The module prints band reference and related tag if defined.
.SS Filter band references by a shortcut
Only band identifiers related to Sentinel\-2 satellite will be
printed.
.br
.nf
\fC
i.band.library pattern=S2
S2_1 Visible (Coastal/Aerosol)
\&...
S2_12 SWIR 2
\fR
.fi
.SS Filter band references by a regular expression
Print all available 2nd bands:
.br
.nf
\fC
i.band.library pattern=.*_2
S2_2 Visible (Blue)
L7_2 Visible (Green)
L8_2 Visible (Blue)
\&...
\fR
.fi
.SS Print extended metadata for specified band identifier
Extended metadata related to the first band of Sentinel\-2 satellite
will be printed.
.br
.nf
\fC
i.band.library \-e pattern=S2_1
description: The Sentinel\-2 A/B bands
shortcut: S2
instruments: MultiSpectral Instrument (MSI) optical and infrared
launched: 23 June 2015 (A); 07 March 2017 (B)
source: https://sentinel.esa.int/web/sentinel/missions/sentinel\-2
    band: 1
        Sentinel 2A:
                central wavelength (nm): 443.9
                bandwidth (nm): 27
        Sentinel 2B:
                central wavelength (nm): 442.3
                bandwidth (nm): 45
        spatial resolution (meters): 60
        tag: Visible (Coastal/Aerosol)
\fR
.fi
.SH KNOWN ISSUES
\fIi.band.library\fR has currently \fBvery limited functionality\fR. Only
system\-defined band references are supported. The final implementation
will support managing (add, modify, delete) user\-defined band
references.
.PP
Only very limited number of band references is currently
defined, namely Sentinel\-2, Landsat7, and Landsat8 satellites. This
will be improved in the near future.
.SH REFERENCES
.RS 4n
.IP \(bu 4n
Google Earth Engine API
.RE
.SH SEE ALSO
\fI
r.semantic.label,
r.info
\fR
.SH AUTHORS
Martin Landa
.br
Development sponsored by mundialis
GmbH & Co. KG (for the openEO
EU H2020 grant 776242)
.SH SOURCE CODE
.PP
Available at:
i.band.library source code
(history)
.PP
Latest change: Tuesday Dec 17 20:17:20 2024 in commit: d962e90c026708a4815ea2b9f46c0e84c17de22d
.PP
Main index |
Imagery index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2025
GRASS Development Team,
GRASS GIS 8.4.1 Reference Manual
