.TH i.signatures 1 "" "GRASS 8.4.1" "GRASS GIS User's Manual"
.SH NAME
\fI\fBi.signatures\fR\fR  \- Manage imagery classification signature files
.SH KEYWORDS
imagery, classification, signatures
.SH SYNOPSIS
\fBi.signatures\fR
.br
\fBi.signatures \-\-help\fR
.br
\fBi.signatures\fR [\-\fBp\fR]  [\fBtype\fR=\fIname\fR]  \fBformat\fR=\fIname\fR  [\fBmapset\fR=\fIname\fR[,\fIname\fR,...]]   [\fBremove\fR=\fIname\fR[,\fIname\fR,...]]   [\fBrename\fR=\fIfrom,to\fR[,\fIfrom,to\fR,...]]   [\fBcopy\fR=\fIfrom,to\fR[,\fIfrom,to\fR,...]]   [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-p\fR" 4m
.br
Print signature files
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBtype\fR=\fIname\fR" 4m
.br
Type of signature file
.br
Options: \fIsig, sigset, libsvm\fR
.IP "\fBformat\fR=\fIname\fR \fB[required]\fR" 4m
.br
Output format
.br
Options: \fIplain, json\fR
.br
Default: \fIplain\fR
.br
\fBplain\fR: Plain text output
.br
\fBjson\fR: JSON (JavaScript Object Notation)
.IP "\fBmapset\fR=\fIname[,\fIname\fR,...]\fR" 4m
.br
Name of mapset to list
.br
Default: current search path
.IP "\fBremove\fR=\fIname[,\fIname\fR,...]\fR" 4m
.br
Name of file(s) to remove
.IP "\fBrename\fR=\fIfrom,to[,\fIfrom,to\fR,...]\fR" 4m
.br
Name of file to rename
.IP "\fBcopy\fR=\fIfrom,to[,\fIfrom,to\fR,...]\fR" 4m
.br
Name of file to copy
.SH DESCRIPTION
\fIi.signatures\fR module allows to manage signature files:
.RS 4n
.IP \(bu 4n
\(dqsig\(dq – generated by i.gensig
for i.maxlik
.IP \(bu 4n
\(dqsigset\(dq – generated by i.gensigset
for i.smap
.RE
The module can perform multiple actions per run. The order of execution
is \(dqcopy\(dq, \(dqremove\(dq, \(dqrename\(dq. When the print flag is specified without
specifying any type of signature files, it would print all signatures
grouped by type.
.SH NOTES
By default the module will list signature files from all mapsets in the
current search path. It is possible to limit listing only to a single
mapset by providing the \(dqmapset\(dq option. The mapset can be also not listed
in the current search path.
.br
Actions \(dqremove\(dq and \(dqrename\(dq operate only on the
current mapset (although accept fully qualified names). The \(dqcopy\(dq action
will accept a signature file name from any mapset as its first argument
(source file to copy).
.SH EXAMPLES
Print names of all signature files:
.br
.nf
\fC
i.signatures \-p
\fR
.fi
Print only signature files of certain type as a JSON:
.br
.nf
\fC
i.signatures \-p type=sigset format=json
\fR
.fi
Delete signature file called \(dqfoo\(dq of type \(dqsig\(dq (i.gensig / i.maxlik).
.br
.nf
\fC
i.signatures remove=foo type=sig
\fR
.fi
Copy signature file \(dqbar\(dq from mapset \(dqbaz\(dq to current mapset
.br
.nf
\fC
i.signatures copy=bar@baz,best_version type=sigset
\fR
.fi
.SH SEE ALSO
\fI
i.gensig
i.gensigset
\fR
.SH AUTHOR
Maris Nartiss
.SH SOURCE CODE
.PP
Available at:
i.signatures source code
(history)
.PP
Latest change: Saturday May 25 03:15:08 2024 in commit: 55b2a2bcccd3fd295e4f20c3e49f6984d61982d3
.PP
Main index |
Imagery index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2025
GRASS Development Team,
GRASS GIS 8.4.1 Reference Manual
