.TH projectionintro 1 "" "GRASS 8.4.1" "GRASS GIS User's Manual"
.SH Projections and spatial transformations in GRASS GIS
.SS Projection management in general
A GRASS project is referenced with a single projection and coordinate system
(or unreferenced as XY project). When creating a new project from an existing
raster or vector map using the tools available from the startup screen or
the map import commands, projection and coordinate system are defined.
To change the projection of maps, a new project has to be created and
the desired maps have to be reprojected into it from the source project
as explained below.
.SS Reprojecting raster maps
Rasters are reprojected using the raster projection tool
\fIr.proj\fR.
The tool is used in the target project to \(dqpull\(dq a map from its source project.
Both projects need to have a projection defined,
i.e., they cannot be XY (unprojected).
.SS Raster map transformation
To transform an unprojected map from a XY project into a projected
project (or another XY project), a forward transformation is performed.
The unreferenced map is geocoded within the XY project by defining
four corner points or by seeking several ground control points
(i.group, i.target,
g.gui.gcp) and then transformed into the
target project (i.rectify). Polynomial
transformation of 1st, 2nd and 3rd order are supported.
.PP
A graphical user interface is provided by wxGUI.
.PP
To simply translate a raster map (without stretching or rotation), the
r.region command can be used.
.SS Vector map projections
Vectors are reprojected using the vector projection tool
\fIv.proj\fR.
The tool is used in the target project to \(dqpull\(dq a map from its source project.
Both projects need to have a projection defined,
i.e., they cannot be XY (unprojected).
.SS Vector map transformation
To transform an unprojected map (e.g. CAD map) into projected coordinates,
a forward transformation is performed. The unreferenced map is imported
into the project with projection and geocoded within this project by
defining  four corner points or by seeking several ground control points.
These points are stored into an ASCII file and then transformed within
the same project (v.transform).
Alternatively, v.rectify rectifies a vector
by computing a coordinate transformation for each object in the vector
based on the control points.
.PP
A graphical user interface is provided by wxGUI.
.SS References
.RS 4n
.IP \(bu 4n
ASPRS Grids and Datum
.IP \(bu 4n
Projections Transform List (PROJ)
.IP \(bu 4n
Coordinate operations by PROJ (projections, conversions, transformations, pipeline operator)
.IP \(bu 4n
MapRef \- The Collection of Map Projections and Reference Systems for Europe
.IP \(bu 4n
Information and Service System for European Coordinate Reference Systems \- CRS
.RE
.SS See also
.RS 4n
.IP \(bu 4n
Introduction into raster data processing
.IP \(bu 4n
Introduction into 3D raster data (voxel) processing
.IP \(bu 4n
Introduction into vector data processing
.IP \(bu 4n
Introduction into image processing
.IP \(bu 4n
Introduction into temporal data processing
.IP \(bu 4n
Database management
.IP \(bu 4n
Graphical User Interface
.RE
.SH SOURCE CODE
.PP
Available at:
Projections and spatial transformations in GRASS GIS source code
(history)
.PP
Latest change: Wednesday Feb 12 18:02:31 2025 in commit: 37997e1712fd75574760e45a2c3c524b33893768
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2025
GRASS Development Team,
GRASS GIS 8.4.1 Reference Manual
