.TH psdriver 1 "" "GRASS 8.4.1" "GRASS GIS User's Manual"
.SH PostScript DISPLAY DRIVER
\fIPS display driver\fR to create PostScript files.
.SH DESCRIPTION
The PS driver generates a PostScript file from GRASS display commands.
.SH USAGE
.SS Environment variables
The PS driver can be enabled by setting \fBGRASS_RENDER_IMMEDIATE\fR
variable, eg.
.br
.nf
\fC
export GRASS_RENDER_IMMEDIATE=ps
\fR
.fi
Several environment variables affect the operation of the PS driver:
.RS 4n
.IP \(bu 4n
\fBGRASS_RENDER_WIDTH=xxx\fR
.br
the width of the image map (default is 640).
.IP \(bu 4n
\fBGRASS_RENDER_HEIGHT=yyy\fR
.br
the height of the image map (default is 480).
.IP \(bu 4n
\fBGRASS_RENDER_TRUECOLOR=[TRUE|FALSE]\fR
.br
sets true\-color support. Default is FALSE.
.IP \(bu 4n
\fBGRASS_RENDER_FILE\fR
.br
name of output file. If it ends with \(dq.eps\(dq an EPS file
will be created.
.IP \(bu 4n
\fBGRASS_RENDER_PS_PAPER\fR
.br
sets the screen dimensions and margins to
fit a standard paper size, see also GRASS_RENDER_WIDTH, GRASS_RENDER_HEIGHT.
.IP \(bu 4n
\fBGRASS_RENDER_PS_LANDSCAPE\fR
.br
if \fCTRUE\fR, the screen is rotated 90 degrees
counter\-clockwise so that a \(dqlandscape\(dq screen fits better on
\(dqportrait\(dq paper.
.IP \(bu 4n
\fBGRASS_RENDER_PS_HEADER\fR
.br
if \fCFALSE\fR, the output is appended to any existing file,
and no prolog or setup sections are generated.
.IP \(bu 4n
\fBGRASS_RENDER_PS_TRAILER\fR
.br
if \fCFALSE\fR, no trailer section is generated.
.RE
.SS Example
.br
.nf
\fC
export GRASS_RENDER_IMMEDIATE=ps
export GRASS_RENDER_TRUECOLOR=TRUE
g.region raster=elevation
d.rast elevation
d.vect roadsmajor color=red
\fR
.fi
This writes a file named \fCmap.ps\fR in your current directory.
.SH NOTES
The resolution of the output files is defined by current region
extents. Use \fCg.region \-p\fR to get the number of rows and cols
and use the environment variables to set the image size. If you would
like a larger image, multiply both rows and cols by the same whole
number to preserve the aspect ratio.
.PP
GRASS_RENDER_TRUECOLOR requires either PostScript level 2 or level 1 plus the
colorimage and setrgbcolor operators (this is the case for colour
printers which pre\-date level 2 PostScript).
.PP
Masked images (\fCd.rast\fR, \fCd.rgb\fR, \fCd.his \-n\fR)
require PostScript level 3.
.SH SEE ALSO
\fI
Cairo driver,
PNG driver,
HTML driver,
variables
\fR
.br
.br
\fI
d.rast,
d.vect,
d.mon,
d.erase,
d.redraw
\fR
.SH AUTHOR
Glynn Clements, 2007
.SH SOURCE CODE
.PP
Available at:
PostScript DISPLAY DRIVER source code
(history)
.PP
Latest change: Tuesday Dec 17 20:17:20 2024 in commit: d962e90c026708a4815ea2b9f46c0e84c17de22d
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2025
GRASS Development Team,
GRASS GIS 8.4.1 Reference Manual
