.TH r3.mask 1 "" "GRASS 8.4.1" "GRASS GIS User's Manual"
.SH NAME
\fI\fBr3.mask\fR\fR  \- Establishes the current working 3D raster mask.
.SH KEYWORDS
raster3d, mask, null data, no\-data, voxel
.SH SYNOPSIS
\fBr3.mask\fR
.br
\fBr3.mask \-\-help\fR
.br
\fBr3.mask\fR \fBmap\fR=\fIstring\fR  [\fBmaskvalues\fR=\fIval[\-val]\fR[,\fIval[\-val]\fR,...]]   [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBmap\fR=\fIstring\fR \fB[required]\fR" 4m
.br
3D raster map with reference values
.IP "\fBmaskvalues\fR=\fIval[\-val][,\fIval[\-val]\fR,...]\fR" 4m
.br
List of cell values to be masked out
.SH DESCRIPTION
\fIr3.mask\fR facilitates the creation of a raster3d
\(dqMASK\(dq map to control raster3d operations.
The raster3d \fImap\fR is used as the reference map.
Cells in the mask are marked as \(dqmask out\(dq if the corresponding cell in
\fImap\fR contains a value in the range specified with \fImaskvalues\fR.
.SH NOTES
Before a new 3D\-mask can be created the existing mask has to be removed
with \fIg.remove\fR.
.SH SEE ALSO
\fI
g.remove
\fR
.SH AUTHORS
Roman Waupotitsch, Michael Shapiro,
Helena Mitasova, Bill Brown, Lubos Mitas,
Jaro Hofierka
.SH SOURCE CODE
.PP
Available at:
r3.mask source code
(history)
.PP
Latest change: Tuesday Dec 17 20:17:20 2024 in commit: d962e90c026708a4815ea2b9f46c0e84c17de22d
.PP
Main index |
3D raster index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2025
GRASS Development Team,
GRASS GIS 8.4.1 Reference Manual
