.TH r3.out.netcdf 1 "" "GRASS 8.4.1" "GRASS GIS User's Manual"
.SH NAME
\fI\fBr3.out.netcdf\fR\fR  \- Export a 3D raster map as netCDF file.
.SH KEYWORDS
raster3d, export, output, netCDF, voxel
.SH SYNOPSIS
\fBr3.out.netcdf\fR
.br
\fBr3.out.netcdf \-\-help\fR
.br
\fBr3.out.netcdf\fR [\-\fBpm\fR] \fBinput\fR=\fIname\fR \fBoutput\fR=\fIname\fR  [\fBnull\fR=\fIfloat\fR]   [\-\-\fBoverwrite\fR]  [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-p\fR" 4m
.br
Export projection information as wkt and proj4 parameter
.IP "\fB\-m\fR" 4m
.br
Use 3D raster mask (if exists) with input map
.IP "\fB\-\-overwrite\fR" 4m
.br
Allow output files to overwrite existing files
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBinput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name of input 3D raster map
.IP "\fBoutput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name for netCDF output file
.IP "\fBnull\fR=\fIfloat\fR" 4m
.br
The value to be used for null values, default is the netCDF standard
.SH DESCRIPTION
The module \fIr3.out.netcdf\fR exports a 3D raster map as netCDF file.
Maps are valid 3D raster maps in the current mapset search path. The
\fIoutput\fR parameter is the name of a netCDF file that will be
written in the current working directory. The module is sensitive
to mapset region settings (set with \fIg.region\fR) and the vertical unit settings
of the 3D raster map. The vertical unit can be set with r3.support.
.SH NOTES
The resulting netCDF file will have time as third dimension in case a temporal
vertical unit is specified for the input map, otherwise the third dimension is assumed as spatial.
If the 3D raster map has a time stamp with absolute time, the start time will be
used as starting point for the netCDF time series. If the absolute time stamp is missing
the date \(dqJan. 01. 1900 00:00:00\(dq will be used as default. In case of relative time stamp no start time
is set in the netCDF file. The number of depths of the 3D raster map are the number of time slices
in the netCDF file. You can use \fIt.rast.to.rast3\fR to convert a
space time raster dataset into a 3D raster map representing a space time voxel
cube, then export the raster time series as netCDF file.
.PP
Spatial coordinates are exported as cell centered coordinates. The projection can be optionally stored
in the metadata as \fIcrs\fR attributes .
The netCDF projection metadata storage follows the spatial_ref GDAL/netCDF suggestion
here
and the netCDF CF 1.6 convention
here
using WKT projection information. Additional a PROJ string is
stored in the \fIcrs\fR attribute section.
The export of projection parameters is suppressed when the XY\-projection is set.
.PP
The range of the 3D raster map is set in the netCDF output file. Optionally a the netCDF missing value and
_FillValue can be set using the \fInull\fR option. As default the netCDF floating point _FillValues are used
to fill empty cell.
.PP
The netCDF library must be installed on the system and activated at configuration time to compile this module.
.SH EXAMPLES
.br
.nf
\fC
g.region s=\-90 n=90 w=\-180 e=180 b=0 t=5 res=10 res3=10 tbres=1 \-p3
#####################################################################
# We create a simple volume map with floating point values
#####################################################################
r3.mapcalc \-\-o expr=\(dqvolume_float = float(col() + row() + depth())\(dq
r3.info volume_float
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
 | Layer:    volume_float                   Date: Thu Jun 14 08:40:56 2012    |
 | Mapset:   PERMANENT                      Login of Creator: soeren          |
 | Project:  TestLL                                                           |
 | DataBase: /1/soeren/grassdata                                              |
 | Title:    volume_float                                                     |
 | Units:    none                                                             |
 | Vertical unit: units                                                       |
 | Timestamp: none                                                            |
 |\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-|
 |                                                                            |
 |   Type of Map:  3d cell              Number of Categories: 0               |
 |   Data Type:    FCELL                                                      |
 |   Rows:         18                                                         |
 |   Columns:      36                                                         |
 |   Depths:       5                                                          |
 |   Total Cells:  3240                                                       |
 |   Total size:           10114 Bytes                                        |
 |   Number of tiles:      1                                                  |
 |   Mean tile size:       10114 Bytes                                        |
 |   Tile size in memory:  12960 Bytes                                        |
 |   Number of tiles in x, y and  z:   1, 1, 1                                |
 |   Dimension of a tile in x, y, z:   36, 18, 5                              |
 |                                                                            |
 |        Projection: Latitude\-Longitude (zone 0)                             |
 |            N:        90N    S:        90S   Res:    10                     |
 |            E:       180E    W:       180W   Res:    10                     |
 |            T:          5    B:          0   Res:     1                     |
 |   Range of data:   min =          3 max =         59                       |
 |                                                                            |
 |   Data Source:                                                             |
 |                                                                            |
 |                                                                            |
 |                                                                            |
 |   Data Description:                                                        |
 |    generated by r3.mapcalc                                                 |
 |                                                                            |
 |   Comments:                                                                |
 |    r3.mapcalc expression=\(dqvolume_float = float(col() + row() + depth())\(dq   |
 |                                                                            |
 +\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-+
#####################################################################
# We use the netCDF ncdump tool to have a look at the header
# and coordinates of the exported netCDF file
#####################################################################
r3.out.netcdf \-\-o input=volume_float output=test_float.nc
ncdump \-c test_float.nc
netcdf test_float {
dimensions:
        longitude = 36 ;
        latitude = 18 ;
        z = 5 ;
variables:
        float longitude(longitude) ;
                longitude:units = \(dqdegrees_east\(dq ;
                longitude:long_name = \(dqLongitude values\(dq ;
                longitude:standard_name = \(dqlongitude\(dq ;
                longitude:axis = \(dqX\(dq ;
        float latitude(latitude) ;
                latitude:units = \(dqdegrees_north\(dq ;
                latitude:long_name = \(dqLatitude values\(dq ;
                latitude:standard_name = \(dqlatitude\(dq ;
                latitude:axis = \(dqY\(dq ;
        float z(z) ;
                z:units = \(dqmeter\(dq ;
                z:long_name = \(dqz coordinate of projection\(dq ;
                z:standard_name = \(dqprojection_z_coordinate\(dq ;
                z:positive = \(dqup\(dq ;
                z:axis = \(dqZ\(dq ;
        float volume_float(z, latitude, longitude) ;
                volume_float:valid_min = 3.f ;
                volume_float:valid_max = 59.f ;
// global attributes:
                :Conventions = \(dqCF\-1.5\(dq ;
                :history = \(dqGRASS GIS netCDF export of r3.out.netcdf\(dq ;
data:
 longitude = \-175, \-165, \-155, \-145, \-135, \-125, \-115, \-105, \-95, \-85, \-75,
    \-65, \-55, \-45, \-35, \-25, \-15, \-5, 5, 15, 25, 35, 45, 55, 65, 75, 85, 95,
    105, 115, 125, 135, 145, 155, 165, 175 ;
 latitude = 85, 75, 65, 55, 45, 35, 25, 15, 5, \-5, \-15, \-25, \-35, \-45, \-55,
    \-65, \-75, \-85 ;
 z = 0.5, 1.5, 2.5, 3.5, 4.5 ;
}
#####################################################################
# Exporting the projection specific settings and a null value
#####################################################################
r3.out.netcdf \-\-o \-p null=\-1 input=volume_float output=test_float.nc
ncdump \-c test_float.nc
netcdf test_float {
dimensions:
        longitude = 36 ;
        latitude = 18 ;
        z = 5 ;
variables:
        char crs ;
                crs:crs_wkt = \(dqGEOGCS[\(rs\(dqwgs84\(rs\(dq,DATUM[\(rs\(dqWGS_1984\(rs\(dq,SPHEROID[\(rs\(dqWGS_1984\(rs\(dq,6378137,298.257223563]],PRIMEM[\(rs\(dqGreenwich\(rs\(dq,0],UNIT[\(rs\(dqdegree\(rs\(dq,0.0174532925199433]]\(dq ;
                crs:spatial_ref = \(dqGEOGCS[\(rs\(dqwgs84\(rs\(dq,DATUM[\(rs\(dqWGS_1984\(rs\(dq,SPHEROID[\(rs\(dqWGS_1984\(rs\(dq,6378137,298.257223563]],PRIMEM[\(rs\(dqGreenwich\(rs\(dq,0],UNIT[\(rs\(dqdegree\(rs\(dq,0.0174532925199433]]\(dq ;
                crs:crs_proj4 = \(dq +proj=longlat +no_defs +a=6378137 +rf=298.257223563 +towgs84=0.000,0.000,0.000\(dq ;
        float longitude(longitude) ;
                longitude:units = \(dqdegrees_east\(dq ;
                longitude:long_name = \(dqLongitude values\(dq ;
                longitude:standard_name = \(dqlongitude\(dq ;
                longitude:axis = \(dqX\(dq ;
        float latitude(latitude) ;
                latitude:units = \(dqdegrees_north\(dq ;
                latitude:long_name = \(dqLatitude values\(dq ;
                latitude:standard_name = \(dqlatitude\(dq ;
                latitude:axis = \(dqY\(dq ;
        float z(z) ;
                z:units = \(dqmeter\(dq ;
                z:long_name = \(dqz coordinate of projection\(dq ;
                z:standard_name = \(dqprojection_z_coordinate\(dq ;
                z:positive = \(dqup\(dq ;
                z:axis = \(dqZ\(dq ;
        float volume_float(z, latitude, longitude) ;
                volume_float:valid_min = 3.f ;
                volume_float:valid_max = 59.f ;
                volume_float:missing_value = \-1.f ;
                volume_float:_FillValue = \-1.f ;
                volume_float:grid_mapping = \(dqcrs\(dq ;
// global attributes:
                :Conventions = \(dqCF\-1.5\(dq ;
                :history = \(dqGRASS GIS netCDF export of r3.out.netcdf\(dq ;
data:
 longitude = \-175, \-165, \-155, \-145, \-135, \-125, \-115, \-105, \-95, \-85, \-75,
    \-65, \-55, \-45, \-35, \-25, \-15, \-5, 5, 15, 25, 35, 45, 55, 65, 75, 85, 95,
    105, 115, 125, 135, 145, 155, 165, 175 ;
 latitude = 85, 75, 65, 55, 45, 35, 25, 15, 5, \-5, \-15, \-25, \-35, \-45, \-55,
    \-65, \-75, \-85 ;
 z = 0.5, 1.5, 2.5, 3.5, 4.5 ;
}
#####################################################################
# Assigning time as vertical unit and setting an absolute time stamp
#####################################################################
r3.timestamp map=volume_float date=\(cq1 Jan 2001/5 Jan 2001\(cq
r3.support map=volume_float vunit=\(dqdays\(dq
r3.out.netcdf \-\-o \-p null=\-1 input=volume_float output=test_float.nc
ncdump \-c test_float.nc
netcdf test_float {
dimensions:
        longitude = 36 ;
        latitude = 18 ;
        time = 5 ;
variables:
        char crs ;
                crs:crs_wkt = \(dqGEOGCS[\(rs\(dqwgs84\(rs\(dq,DATUM[\(rs\(dqWGS_1984\(rs\(dq,SPHEROID[\(rs\(dqWGS_1984\(rs\(dq,6378137,298.257223563]],PRIMEM[\(rs\(dqGreenwich\(rs\(dq,0],UNIT[\(rs\(dqdegree\(rs\(dq,0.0174532925199433]]\(dq ;
                crs:spatial_ref = \(dqGEOGCS[\(rs\(dqwgs84\(rs\(dq,DATUM[\(rs\(dqWGS_1984\(rs\(dq,SPHEROID[\(rs\(dqWGS_1984\(rs\(dq,6378137,298.257223563]],PRIMEM[\(rs\(dqGreenwich\(rs\(dq,0],UNIT[\(rs\(dqdegree\(rs\(dq,0.0174532925199433]]\(dq ;
                crs:crs_proj4 = \(dq +proj=longlat +no_defs +a=6378137 +rf=298.257223563 +towgs84=0.000,0.000,0.000\(dq ;
        float longitude(longitude) ;
                longitude:units = \(dqdegrees_east\(dq ;
                longitude:long_name = \(dqLongitude values\(dq ;
                longitude:standard_name = \(dqlongitude\(dq ;
                longitude:axis = \(dqX\(dq ;
        float latitude(latitude) ;
                latitude:units = \(dqdegrees_north\(dq ;
                latitude:long_name = \(dqLatitude values\(dq ;
                latitude:standard_name = \(dqlatitude\(dq ;
                latitude:axis = \(dqY\(dq ;
        int time(time) ;
                time:units = \(dqdays since 2001\-01\-01 00:00:00\(dq ;
                time:long_name = \(dqTime in days\(dq ;
                time:calendar = \(dqgregorian\(dq ;
                time:positive = \(dqup\(dq ;
                time:axis = \(dqT\(dq ;
        float volume_float(time, latitude, longitude) ;
                volume_float:valid_min = 3.f ;
                volume_float:valid_max = 59.f ;
                volume_float:missing_value = \-1.f ;
                volume_float:_FillValue = \-1.f ;
                volume_float:grid_mapping = \(dqcrs\(dq ;
// global attributes:
                :Conventions = \(dqCF\-1.5\(dq ;
                :history = \(dqGRASS GIS netCDF export of r3.out.netcdf\(dq ;
data:
 longitude = \-175, \-165, \-155, \-145, \-135, \-125, \-115, \-105, \-95, \-85, \-75,
    \-65, \-55, \-45, \-35, \-25, \-15, \-5, 5, 15, 25, 35, 45, 55, 65, 75, 85, 95,
    105, 115, 125, 135, 145, 155, 165, 175 ;
 latitude = 85, 75, 65, 55, 45, 35, 25, 15, 5, \-5, \-15, \-25, \-35, \-45, \-55,
    \-65, \-75, \-85 ;
 time = 0, 1, 2, 3, 4 ;
}
\fR
.fi
.SH SEE ALSO
\fI
t.rast.to.rast3,
r3.in.ascii,
g.region
\fR
.SH AUTHORS
Sören Gebbert
.SH SOURCE CODE
.PP
Available at:
r3.out.netcdf source code
(history)
.PP
Latest change: Tuesday Dec 17 20:17:20 2024 in commit: d962e90c026708a4815ea2b9f46c0e84c17de22d
.PP
Main index |
3D raster index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2025
GRASS Development Team,
GRASS GIS 8.4.1 Reference Manual
