.TH topic_imagery 1 "" "GRASS 8.4.1" "GRASS GIS User's Manual"
.SH Topic: imagery
.TS
expand;
lw60 lw1 lw60.
T{
i.band.library
T}	 	T{
Prints available semantic label information used for multispectral data.
T}
.sp 1
T{
r.semantic.label
T}	 	T{
Manages semantic label information assigned to a single raster map or to a list of raster maps.
T}
.sp 1
.TE
.PP
\fISee also the corresponding keyword imagery for additional references.\fR
.PP
Main index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2025
GRASS Development Team,
GRASS GIS 8.4.1 Reference Manual
