.TH v.dissolve 1 "" "GRASS 8.4.1" "GRASS GIS User's Manual"
.SH NAME
\fI\fBv.dissolve.py\fR\fR  \- Dissolves adjacent or overlaping features sharing a common category number or attribute.
.SH KEYWORDS
vector, dissolve, area, line
.SH SYNOPSIS
\fBv.dissolve.py\fR
.br
\fBv.dissolve.py \-\-help\fR
.br
\fBv.dissolve.py\fR \fBinput\fR=\fIname\fR  [\fBlayer\fR=\fIstring\fR]   [\fBcolumn\fR=\fIname\fR]  \fBoutput\fR=\fIname\fR  [\fBaggregate_columns\fR=\fIname\fR[,\fIname\fR,...]]   [\fBaggregate_methods\fR=\fIstring\fR[,\fIstring\fR,...]]   [\fBresult_columns\fR=\fIname\fR[,\fIname\fR,...]]   [\fBaggregate_backend\fR=\fIstring\fR]   [\-\-\fBoverwrite\fR]  [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-\-overwrite\fR" 4m
.br
Allow output files to overwrite existing files
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBinput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name of input vector map
.br
Or data source for direct OGR access
.IP "\fBlayer\fR=\fIstring\fR" 4m
.br
Layer number or name.
.br
Vector features can have category values in different layers. This number determines which layer to use. When used with direct OGR access this is the layer name.
.br
Default: \fI1\fR
.IP "\fBcolumn\fR=\fIname\fR" 4m
.br
Name of attribute column used to dissolve features
.IP "\fBoutput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name for output vector map
.IP "\fBaggregate_columns\fR=\fIname[,\fIname\fR,...]\fR" 4m
.br
Names of attribute columns to get aggregate statistics for
.br
One column name or SQL expression per method if result columns are specified
.IP "\fBaggregate_methods\fR=\fIstring[,\fIstring\fR,...]\fR" 4m
.br
Aggregate statistics method (e.g., sum)
.br
Default is all available basic statistics for a given backend (for sql backend: avg, count, max, min, sum)
.IP "\fBresult_columns\fR=\fIname[,\fIname\fR,...]\fR" 4m
.br
New attribute column names for aggregate statistics results
.br
Defaults to aggregate column name and statistics name and can contain type
.IP "\fBaggregate_backend\fR=\fIstring\fR" 4m
.br
Backend for attribute aggregation
.br
Default is sql unless the provided aggregate methods are for univar
.br
Options: \fIsql, univar\fR
.br
\fBsql\fR: Uses SQL attribute database
.br
\fBunivar\fR: Uses v.db.univar
.SH DESCRIPTION
The \fIv.dissolve\fR module is used to merge adjacent or overlapping
features in a vector map that share the same category value. The
resulting merged feature(s) retain this category value.
.PP
\fI
Figure: Areas with the same attribute value (first image) are merged
into one (second image).
\fR
.PP
Instead of dissolving features based on the category values, the user
can define an integer or string column using the \fBcolumn\fR
parameter. In that case, features that share the same value in that
column are dissolved. Note, the newly created layer does not retain the
category (cat) values from the input layer.
.PP
Note that multiple areas with the same category or the same attribute
value that are not adjacent are merged into one entity, which consists
of multiple features, i.e., a multipart feature.
.SS Attribute aggregation
The attributes of merged areas can be aggregated using various
aggregation methods. The specific methods available depend on the
backend used for aggregation. Two aggregate backends (specified with
the \fBaggregate_backend\fR parameter) are available, \fIunivar\fR
and \fIsql\fR. The backend is determined automatically based on the
requested methods. When the function is one of the \fISQL\fR
build\-in aggregate functions, the \fIsql\fR backend is used.
Otherwise, the \fIunivar\fR backend is used.
.PP
The default behavior is intended for interactive use and
testing. For scripting and other automated usage, explicitly specifying
the backend with the \fBaggregate_backend\fR parameter is strongly
recommended. When choosing, note that the \fIsql\fR aggregate
backend, regardless of the underlying database, will typically perform
significantly better than the \fIunivar\fR backend.
.SS Aggregation using univar backend
When \fIunivar\fR is used, the methods available are the ones which
\fIv.db.univar\fR uses by default, i.e., \fIn\fR, \fImin\fR,
\fImax\fR, \fIrange\fR, \fImean\fR, \fImean_abs\fR,
\fIvariance\fR, \fIstddev\fR, \fIcoef_var\fR, and
\fIsum\fR.
.SS Aggregation using sql backend
When the \fIsql\fR backend is used, the methods depend on the SQL
database backend used for the attribute table of the input vector. For
SQLite, there are at least the following built\-in aggregate
functions: \fIcount\fR, \fImin\fR, \fImax\fR,
\fIavg\fR, \fIsum\fR, and \fItotal\fR.
For PostgreSQL, the list of aggregate
functions is much longer and includes, e.g., \fIcount\fR,
\fImin\fR, \fImax\fR, \fIavg\fR, \fIsum\fR,
\fIstddev\fR, and \fIvariance\fR.
.SS Defining the aggregation method
If only the parameter \fBaggregate_columns\fR is provided, all the
following aggregation statistics are calculated: \fIn\fR,
\fImin\fR, \fImax\fR, \fImean\fR, and \fIsum\fR. If the
\fIunivar\fR backend is specified, all the available methods for the
\fIunivar\fR backend are used.
.PP
The \fBaggregate_methods\fR parameter can be used to specify which
aggregation statistics should be computed. Alternatively, the parameter
\fBaggregate_columns\fR can be used to specify the method using SQL
syntax. This provides the highest flexibility, and it is suitable for
scripting. The SQL statement should specify both the column and the
functions applied, e.g.,
.br
.nf
\fC
\fCaggregate_columns=\(dqsum(cows) / sum(animals)\(dq\fR.
\fR
.fi
.PP
Note that when the \fBaggregate_columns\fR parameter is used, the
\fIsql\fR backend should be used. In addition, the
\fBaggregate_columns\fR and \fBaggregate_methods\fR cannot be used
together.
.PP
For convenience, certain methods, namely \fIn\fR, \fIcount\fR,
\fImean\fR, and \fIavg\fR, are automatically converted to the
appropriate name for the selected backend. However, for scripting, it
is recommended to specify the appropriate method (function) name for
the backend, as the conversion is a heuristic that may change in the
future.
.PP
If the \fBresult_columns\fR is not provided, each method is applied to
each column specified by \fBaggregate_columns\fR. This results in a
column for each of the combinations. These result columns have
auto\-generated names based on the aggregate column and method. For
example, setting the following parameters:
.br
.nf
\fC
aggregate_columns=A,B
aggregate_methods=sum,n
\fR
.fi
.PP
results in the following columns: A_sum, A_n, B_sum, B_n. See
the Examples section.
.PP
If the \fBresult_column\fR is provided, each method is applied only
once to the matching column in the aggregate column list, and the
result will be available under the name of the matching result column.
For example, setting the following parameter:
.br
.nf
\fC
aggregate_columns=A,B
aggregate_methods=sum,max
result_column=sum_a, n_b
\fR
.fi
.PP
results in the column \fIsum_a\fR with the sum of the values of
\fIA\fR and the column \fIn_b\fR with the max of \fIB\fR. Note that
the number of items in \fBaggregate_columns\fR,
\fBaggregate_methods\fR (unless omitted), and \fBresult_column\fR
needs to match, and no combinations are created on the fly. See
the Examples section.
.PP
For scripting, it is recommended to specify all resulting column names,
while for interactive use, automatically created combinations are
expected to be beneficial, especially for exploratory analysis.
.PP
The type of the result column is determined based on the method
selected. For \fIn\fR and \fIcount\fR, the type is INTEGER and
for all other methods, it is DOUBLE. Aggregate methods that produce
other types require the type to be specified as part of the
\fBresult_columns\fR. A type can be provided in \fBresult_columns\fR
using the SQL syntax \fCname type\fR, e.g., \fCsum_of_values
double precision\fR. Type specification is mandatory when SQL
syntax is used in \fBaggregate_columns\fR (and
\fBaggregate_methods\fR is omitted).
.SH NOTES
GRASS defines a vector area as a composite entity consisting of a set
of closed boundaries and a centroid. The centroids must contain a
category number (see \fIv.centroids\fR), this number is linked to
area attributes and database links.
.PP
Multiple attributes may be linked to a single vector entity through
numbered fields referred to as layers. Refer to \fIv.category\fR for
more details.
.PP
Merging of areas can also be accomplished using \fCv.extract \-d\fR
which provides some additional options. In fact, \fIv.dissolve\fR is
simply a front\-end to that module. The use of the \fIcolumn\fR
parameter adds a call to \fIv.reclass\fR before.
.SH EXAMPLES
.SS Basic use
.br
.nf
\fC
v.dissolve input=undissolved output=dissolved
\fR
.fi
.SS Dissolving based on column attributes
North Carolina data set:
.br
.nf
\fC
g.copy vect=soils_general,mysoils_general
v.dissolve mysoils_general output=mysoils_general_families column=GSL_NAME
\fR
.fi
.SS Dissolving adjacent SHAPE files to remove tile boundaries
If tile boundaries of adjacent maps (e.g. CORINE Landcover SHAPE files)
have to be removed, an extra step is required to remove duplicated
boundaries:
.br
.nf
\fC
# patch tiles after import:
v.patch \-e \(gag.list type=vector pat=\(dqclc2000_*\(dq separator=\(dq,\(dq\(ga out=clc2000_patched
# remove duplicated tile boundaries:
v.clean clc2000_patched out=clc2000_clean tool=snap,break,rmdupl thresh=.01
# dissolve based on column attributes:
v.dissolve input=clc2000_clean output=clc2000_final col=CODE_00
\fR
.fi
.SS Attribute aggregation
While dissolving, we can aggregate attribute values of the original features.
Let\(cqs aggregate area in acres (ACRES) of all municipal boundaries
(boundary_municp) in the full NC dataset while dissolving common boundaries
based on the name in the DOTURBAN_N column
(long lines are split with backslash marking continued line as in Bash):
.br
.nf
\fC
v.dissolve input=boundary_municp column=DOTURBAN_N output=municipalities \(rs
    aggregate_columns=ACRES
\fR
.fi
.PP
To inspect the result, we will use \fIv.db.select\fR retrieving only one row
for \fCDOTURBAN_N == \(cqWadesboro\(cq\fR:
.br
.nf
\fC
v.db.select municipalities where=\(dqDOTURBAN_N == \(cqWadesboro\(cq\(dq separator=tab
\fR
.fi
.PP
The resulting table may look like this:
.br
.nf
\fC
cat  DOTURBAN_N    ACRES_n    ACRES_min    ACRES_max    ACRES_mean    ACRES_sum
66   Wadesboro     2          634.987      3935.325     2285.156      4570.312
\fR
.fi
.PP
The above created multiple columns for each of the statistics computed
by default. We can limit the number of statistics computed by specifying
the method which should be used:
.br
.nf
\fC
v.dissolve input=boundary_municp column=DOTURBAN_N output=municipalities_2 \(rs
    aggregate_columns=ACRES aggregate_methods=sum
\fR
.fi
.PP
The above gives a single column with the sum for all values in the ACRES column
for each group of original features which had the same value in the DOTURBAN_N
column and are now dissolved (merged) into one.
.SS Aggregating multiple attributes
Expanding on the previous example, we can compute values for multiple columns
at once by adding more columns to the \fBaggregate_columns\fR option.
We will compute average of values in the NEW_PERC_G column:
.br
.nf
\fC
v.dissolve input=boundary_municp column=DOTURBAN_N output=municipalities_3 \(rs
    aggregate_columns=ACRES,NEW_PERC_G aggregate_methods=sum,avg
\fR
.fi
.PP
By default, all methods specified in the \fBaggregate_methods\fR are
applied to all columns, so result of the above is four columns. While
this is convenient for getting multiple statistics for similar columns
(e.g. averages and standard deviations of multiple population
statistics columns), in our case, each column is different and each
aggregate method should be applied only to its corresponding column.
.PP
The \fIv.dissolve\fR module will apply each aggregate method only to
the corresponding column when column names for the results are
specified manually with the \fBresult_columns\fR option:
.br
.nf
\fC
v.dissolve input=boundary_municp column=DOTURBAN_N output=municipalities_4 \(rs
    aggregate_columns=ACRES,NEW_PERC_G aggregate_methods=sum,avg \(rs
    result_columns=acres,new_perc_g
\fR
.fi
.PP
Now we have full control over what columns are created, but we also
need to specify an aggregate method for each column even when the
aggregate methods are the same:
.br
.nf
\fC
v.dissolve input=boundary_municp column=DOTURBAN_N output=municipalities_5 \(rs
    aggregate_columns=ACRES,DOTURBAN_N,TEXT_NAME aggregate_methods=sum,count,count \(rs
    result_columns=acres,number_of_parts,named_parts
\fR
.fi
.PP
While it is often not necessary to specify aggregate methods or names
for interactive exploratory analysis, specifying both
\fBaggregate_methods\fR and \fBresult_columns\fR manually is a best
practice for scripting (unless SQL syntax is used for
\fBaggregate_columns\fR, see below).
.SS Aggregating using SQL syntax
The aggregation can be done also using the full SQL syntax and set of
aggregate functions available for a given attribute database backend.
Here, we will assume the default SQLite database backend for attribute.
.PP
Modifying the previous example, we will now specify the SQL aggregate
function calls explicitly instead of letting \fIv.dissolve\fR
generate them for us. We will compute sum of the ACRES column using
\fCsum(ACRES)\fR (alternatively, we could use SQLite specific
\fCtotal(ACRES)\fR which returns zero even when all values are
NULL). Further, we will count number of aggregated (i.e., dissolved)
parts using \fCcount(*)\fR which counts all rows regardless of
NULL values. Then, we will count all unique names of parts as
distinguished by the MB_NAME column using \fCcount(distinct
MB_NAME)\fR. Finally, we will collect all these names into a
comma\-separated list using \fCgroup_concat(MB_NAME)\fR:
.br
.nf
\fC
v.dissolve input=boundary_municp column=DOTURBAN_N output=municipalities_6 \(rs
    aggregate_columns=\(dqtotal(ACRES),count(*),count(distinct MB_NAME),group_concat(MB_NAME)\(dq \(rs
    result_columns=\(dqacres REAL,named_parts INTEGER,unique_names INTEGER,names TEXT\(dq
\fR
.fi
.PP
Here, \fIv.dissolve\fR doesn\(cqt make any assumptions about the
resulting column types, so we specified both named and the type of each
column.
.PP
When working with general SQL syntax, \fIv.dissolve\fR turns off its
checks for number of aggregate and result columns to allow for all SQL
syntax to be used for aggregate columns. This allows us to use also
functions with multiple parameters, for example specify separator to be
used with \fIgroup_concat\fR:
.br
.nf
\fC
v.dissolve input=boundary_municp column=DOTURBAN_N output=municipalities_7 \(rs
    aggregate_columns=\(dqgroup_concat(MB_NAME, \(cq;\(cq)\(dq \(rs
    result_columns=\(dqnames TEXT\(dq
\fR
.fi
.PP
To inspect the result, we will use \fIv.db.select\fR retrieving only
one row for \fCDOTURBAN_N == \(cqWadesboro\(cq\fR:
.br
.nf
\fC
v.db.select municipalities_7 where=\(dqDOTURBAN_N == \(cqWadesboro\(cq\(dq separator=tab
\fR
.fi
.PP
The resulting table may look like this:
.br
.nf
\fC
cat	DOTURBAN_N	names
66	Wadesboro	Wadesboro;Lilesville
\fR
.fi
.SH SEE ALSO
\fI
v.category,
v.centroids,
v.extract,
v.reclass,
v.db.univar,
v.db.select
\fR
.SH AUTHORS
M. Hamish Bowman, Department of Marine Science, Otago University, New Zealand (module)
.br
Markus Neteler (column support)
.br
Trevor Wiens (help page)
.br
Vaclav Petras, NC State University, Center for Geospatial Analytics, GeoForAll Lab (aggregate statistics)
.SH SOURCE CODE
.PP
Available at:
v.dissolve source code
(history)
.PP
Latest change: Tuesday Dec 17 20:17:20 2024 in commit: d962e90c026708a4815ea2b9f46c0e84c17de22d
.PP
Main index |
Vector index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2025
GRASS Development Team,
GRASS GIS 8.4.1 Reference Manual
