.TH v.external.out 1 "" "GRASS 8.4.1" "GRASS GIS User's Manual"
.SH NAME
\fI\fBv.external.out\fR\fR  \- Defines vector output format.
.SH KEYWORDS
vector, export, output, external, OGR, PostGIS
.SH DESCRIPTION
\fIv.external.out\fR instructs GRASS to write vector maps in
external data format (e.g. ESRI Shapefile, Mapinfo, and others)
using OGR library. PostGIS data can
be also written by
built\-in GRASS\-PostGIS
data provider.
.SH NOTES
Number of available output formats (\fCv.external.out \-f\fR)
depends on OGR installation. \(cqPostgreSQL\(cq format is presented also
when GRASS comes with PostgreSQL support (check for \(cq\-\-with\-postgres\(cq
in \fCg.version \-b\fR output).
.PP
To store geometry and attribute data in PostGIS database (\(cqPostgreSQL\(cq
format) GRASS uses built\-in \fIGRASS\-PostGIS data
provider\fR. PostGIS data can be written also by OGR library
when \fCGRASS_VECTOR_OGR\fR environmental variable is defined or
GRASS is not compiled with PostgreSQL support.
.PP
Creation \fBoptions\fR refer to the output format specified
by \fBformat\fR option. See the list of valid creation options
at OGR formats
specification page, example
for ESRI
Shapefile
or PostgreSQL/PostGIS
format (section \(dqLayer Creation Options\(dq). Options are
comma\-separated pairs (\fCkey=value\fR), the options are
case\-insensitive,
eg. \fCoptions=\(dqSCHEMA=myschema,FID=cat\(dq\fR.
.SS PostgreSQL/PostGIS Creation Options
Note that built\-in \fIGRASS\-PostGIS data provider\fR
(\fBformat=PostgreSQL\fR) supports different creation \fBoptions\fR
compared to PostgreSQL/PostGIS driver from OGR library:
.RS 4n
.IP \(bu 4n
\fCSCHEMA=<name>\fR \- name of schema where to create
feature tables. If schema doesn\(cqt exists, it\(cqs automatically created
when writing PostGIS data.
.IP \(bu 4n
\fCFID=<column>\fR \- name of column which will be used as
primary key (feature id), default: \fCfid\fR
.IP \(bu 4n
\fCGEOMETRY_NAME=<column>\fR name of column which will
be used for storing geometry data in feature table, default: \fCgeom\fR
.IP \(bu 4n
\fCSPATIAL_INDEX=YES|NO\fR \- enable/disable spatial index on geometry column, default: YES
.IP \(bu 4n
\fCPRIMARY_KEY=YES|NO\fR \- enable/disable primary key on FID column, default: YES
.IP \(bu 4n
\fCSRID=<value>\fR \- spatial reference identifier,
default: not defined
.IP \(bu 4n
\fCTOPOLOGY=YES|NO\fR \- enable/disable
native PostGIS
topology, default: NO
.RE
Options relevant only to topological output (\fCTOPOLOGY=YES\fR):
.RS 4n
.IP \(bu 4n
\fCTOPOSCHEMA_NAME=<schema name>\fR \- name of PostGIS
Topology schema (relevant only for \fCTOPOLOGY=YES\fR),
default: \fCtopo_<input>\fR
.IP \(bu 4n
\fCTOPOGEOM_NAME=<column>\fR \- name of column which
will be used for storing topogeometry data in feature table,
default: \fCtopo\fR
.IP \(bu 4n
\fCTOPO_TOLERANCE=<value>\fR \- tolerance for PostGIS
Topology schema,
see CreateTopology
function for defails, default: \fC0\fR
.IP \(bu 4n
\fCTOPO_GEO_ONLY=YES|NO\fR \- store in PostGIS Topology schema
only data relevant to Topo\-Geo data model, default: \fCNO\fR
.IP \(bu 4n
\fCSIMPLE_FEATURE=YES|NO\fR \- build simple features geometry
in \fCGEOMETRY_NAME\fR column from topogeometry data, default:
NO
.RE
Note that topological output requires \fBPostGIS version 2 or later\fR.
.SH EXAMPLES
.SS ESRI Shapefile
\fIv.external.out\fR can be used along with
\fIv.external\fR to process external
geodata in GRASS while writing out the results directly eg. in ESRI
Shapefile format:
.br
.nf
\fC
# register Shapefile in GRASS mapset:
v.external input=/path/to/shapefiles layer=cities
# define output directory for GRASS calculation results:
v.external.out output=$HOME/gisoutput
# do something (here: spatial query), write output directly as Shapefile
v.select ainput=cities atype=point binput=forests btype=area operator=within output=fcities
\fR
.fi
Current settings can be printed using \fB\-p\fR or \fB\-g\fR flag.
.br
.nf
\fC
v.external.out \-p
output: /path/to/home/gisoutput
format: ESRI Shapefile
\fR
.fi
.SS PostGIS (simple features)
PostGIS data can be accessed directly using \fIGRASS\-PostGIS data
provider\fR (GRASS must be compiled with PostgreSQL support).
.br
.nf
\fC
# register PostGIS table in GRASS mapset:
v.external output=PG:dbname=gisdb layer=cities
# define output PostGIS database for GRASS calculation results stored as simple features:
v.external.out output=PG:dbname=gisdb format=PostgreSQL
# do some processing...
\fR
.fi
\fINote:\fR If the environment variable \fCGRASS_VECTOR_OGR\fR
is defined, or GRASS is compiled without PostgreSQL support then GRASS
will use PostgreSQL driver from OGR library for reading and writing
PostGIS data.
.SS PostGIS Topology
.br
.nf
\fC
# define output PostGIS database for GRASS calculation results stored as topological elements:
v.external.out output=PG:dbname=gisdb format=PostgreSQL options=topology=YES
# do some processing...
\fR
.fi
\fINote:\fR PostGIS topological access is supported only in
built\-in \fIGRASS\-PostGIS data provider\fR.
.SS GRASS native format
To restore original settings, ie. use the GRASS native format, type:
.br
.nf
\fC
v.external.out \-r
\fR
.fi
.SS Restore settings
Current settings can be stored to file by specifying \fBoutput\fR option.
.br
.nf
\fC
# define output PostGIS database for GRASS calculation with
# results stored as topological elements:
v.external.out output=PG:dbname=gisdb format=PostgreSQL \(rs
  options=topology=YES savesettings=gisdb_topo.txt
# ... and do some processing in PostGIS Topology
\fR
.fi
Back to native format:
.br
.nf
\fC
v.external.out \-r
# do some processing in native format
\fR
.fi
Restore previous settings from \(dqgisdb_topo.txt\(dq file by
specifying \fBloadsettings\fR option.
.br
.nf
\fC
v.external.out loadsettings=gisdb_topo.txt
# ... and do some processing in PostGIS Topology
\fR
.fi
.SH REFERENCES
.RS 4n
.IP \(bu 4n
GRASS\-OGR data provider
.IP \(bu 4n
OGR vector library C API documentation
.IP \(bu 4n
GRASS\-PostGIS data provider
.IP \(bu 4n
libpq \- C Library
.RE
.SH SEE ALSO
\fI
v.external,
v.in.ogr,
v.out.ogr,
v.out.postgis
\fR
.PP
See
also GRASS user wiki page for more examples.
.SH AUTHOR
Martin Landa, Czech Technical University in Prague, Czech Republic
(development supported by Fondazione Edmund Mach and Comune di Trento, Italy)
.SH SOURCE CODE
.PP
Available at:
v.external.out source code
(history)
.PP
Latest change: Tuesday Dec 17 20:17:20 2024 in commit: d962e90c026708a4815ea2b9f46c0e84c17de22d
.PP
Main index |
Vector index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2025
GRASS Development Team,
GRASS GIS 8.4.1 Reference Manual
