.TH v.fill.holes 1 "" "GRASS 8.4.1" "GRASS GIS User's Manual"
.SH NAME
\fI\fBv.fill.holes\fR\fR  \- Fill holes in areas by keeping only outer boundaries
.SH KEYWORDS
vector, geometry, fill, exterior, ring, perimeter
.SH SYNOPSIS
\fBv.fill.holes\fR
.br
\fBv.fill.holes \-\-help\fR
.br
\fBv.fill.holes\fR \fBinput\fR=\fIname\fR  [\fBlayer\fR=\fIstring\fR]   [\fBcats\fR=\fIrange\fR]   [\fBwhere\fR=\fIsql_query\fR]  \fBoutput\fR=\fIname\fR  [\-\-\fBoverwrite\fR]  [\-\-\fBhelp\fR]  [\-\-\fBverbose\fR]  [\-\-\fBquiet\fR]  [\-\-\fBui\fR]
.SS Flags:
.IP "\fB\-\-overwrite\fR" 4m
.br
Allow output files to overwrite existing files
.IP "\fB\-\-help\fR" 4m
.br
Print usage summary
.IP "\fB\-\-verbose\fR" 4m
.br
Verbose module output
.IP "\fB\-\-quiet\fR" 4m
.br
Quiet module output
.IP "\fB\-\-ui\fR" 4m
.br
Force launching GUI dialog
.SS Parameters:
.IP "\fBinput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name of input vector map
.br
Or data source for direct OGR access
.IP "\fBlayer\fR=\fIstring\fR" 4m
.br
Layer number or name
.br
Vector features can have category values in different layers. This number determines which layer to use. When used with direct OGR access this is the layer name.
.br
Default: \fI1\fR
.IP "\fBcats\fR=\fIrange\fR" 4m
.br
Category values
.br
Example: 1,3,7\-9,13
.IP "\fBwhere\fR=\fIsql_query\fR" 4m
.br
WHERE conditions of SQL statement without \(cqwhere\(cq keyword
.br
Example: income < 1000 and population >= 10000
.IP "\fBoutput\fR=\fIname\fR \fB[required]\fR" 4m
.br
Name for output vector map
.SH DESCRIPTION
\fIv.fill.holes\fR fills empty spaces inside areas, specifically
it preserves areas with centroids while areas without centroids,
which typically represent holes, are removed.
\fIv.fill.holes\fR goes over all areas in a vector map
and it preserves only outer boundaries of each area
while removing inner boundaries which are considered holes.
The holes become part of the area which contained them.
No boundaries of these holes are preserved.
.br
\fI
Figure: Holes inside areas are removed. (a) Original areas with holes and (b) the same areas but with holes filled.
\fR
In case areas have empty space in between them,
i.e., there are holes in the overall coverage, but not in the areas themselves,
\fIv.fill.holes\fR can\(cqt assign this empty space to either of these areas
because it does not know which area this empty space should belong to.
If the space needs to be filled, this can be resolved by merging the areas
around the empty space into one by dissolving their common boundaries.
This turns the empty space into a hole inside one single area
which turns the situation into a case of one area with a hole.
.br
\fI
Figure: Empty space in between two areas does not belong to either area,
so it is filled only after the boundaries between areas are dissolved,
i.e., areas merged into one.
(a) Original areas with space in between,
(b) one area with a hole after dissolving the common boundary, and
(c) hole filled.
\fR
.SS Topology
Strictly speaking, in the GRASS topological model, an area is a closed boundary
(or a series of connected closed boundaries) which may have a centroid.
If it has a centroid, it is rendered as a filled area in displays and
this is what is usually considered an area from the user perspective.
These are the areas where \fIv.fill.holes\fR preserves the associated outer boundary (or boundaries).
Other closed boundaries, i.e., those without a centroid, are not carried over to the output.
All other features are removed including points and lines.
.SS Attributes
If a specific layer is selected, attributes for that layer are preserved
for the areas based on the category or categories associated with each area.
By default, layer number 1 is selected.
In case there are attribute tables associated with other layers or attributes
associated with categories of other features than areas with centroids,
this attribute data is not carried over to the output just like the
corresponding geometries.
.SH EXAMPLE
The \fIlakes\fR vector map in the North Carolina sample dataset
represents islands inside lakes as areas distinguished by attributes.
To demonstrate \fIv.fill.holes\fR, we will first extract only the
lakes which will create holes where the islands were located.
Then, we will fill the holes created in the lakes to get
the whole perimeter of the lakes including islands.
Remove the islands by extracting everything else (results in holes):
.br
.nf
\fC
v.extract input=lakes where=\(dqFTYPE != \(cqROCK/ISLAND\(cq\(dq output=lakes_only
\fR
.fi
Remove the holes:
.br
.nf
\fC
v.fill.holes input=lakes_only output=lakes_filled
\fR
.fi
.br
\fI
Figure: The filled lake (blue) and borders of the original lakes with islands removed (light blue).
Figure shows a smaller area in the north of the data extent.
\fR
.SH SEE ALSO
.RS 4n
.IP \(bu 4n
\fIv.dissolve\fR
for removing common boundaries based on attributes,
.IP \(bu 4n
\fIv.clean\fR
for removing topological issues,
.IP \(bu 4n
\fIr.fillnulls\fR
for filling empty spaces in raster maps using interpolation,
.IP \(bu 4n
\fIr.fill.stats\fR
for filling empty spaces in raster maps using statistics.
.RE
.SH AUTHOR
Vaclav Petras, NCSU Center for Geospatial Analytics, GeoForAll Lab
.SH SOURCE CODE
.PP
Available at:
v.fill.holes source code
(history)
.PP
Latest change: Tuesday Apr 23 10:45:15 2024 in commit: f8115df1219e784a7136e7609f4c9bb16d928e2f
.PP
Main index |
Vector index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2025
GRASS Development Team,
GRASS GIS 8.4.1 Reference Manual
