.TH wxGUI.components 1 "" "GRASS 8.4.1" "GRASS GIS User's Manual"
.SH wxGUI Components
.SH KEYWORDS
general, GUI
.SH DESCRIPTION
List of available \fIwxGUI\fR components:
.RS 4n
.IP \(bu 4n
Module dialogs
.IP \(bu 4n
3D Viewer (nviz)
.IP \(bu 4n
Animation tool,
available as a command line tool \fIg.gui.animation\fR
.IP \(bu 4n
Attribute Table Manager,
available also as a command line tool \fIg.gui.dbmgr\fR
.IP \(bu 4n
Cartographic Composer,
available also as a command line tool \fIg.gui.psmap\fR
.IP \(bu 4n
Data Catalog,
available also as a command line tool \fIg.gui.datacatalog\fR
.IP \(bu 4n
Graphical Modeler,
available also as a command line tool \fIg.gui.gmodeler\fR
.IP \(bu 4n
Ground Control Points Manager,
available also as a command line tool \fIg.gui.gcp\fR
.IP \(bu 4n
Interactive Scatter Plot Tool
.IP \(bu 4n
Map Swipe,
available also as a command line tool \fIg.gui.mapswipe\fR
.IP \(bu 4n
Supervised Classification Tool,
available also as a command line tool \fIg.gui.iclass\fR
.IP \(bu 4n
Configuration tool for r.li modules, \fIg.gui.rlisetup\fR
.IP \(bu 4n
Timeline Tool,
available also as a command line tool \fIg.gui.timeline\fR
.IP \(bu 4n
Temporal Plot Tool,
available also as a command line tool \fIg.gui.tplot\fR
.IP \(bu 4n
Vector Digitizer,
available also as a command line tool \fIg.gui.vdigit\fR
.IP \(bu 4n
Raster Digitizer
available also as a command line tool \fIg.gui.rdigit\fR
.IP \(bu 4n
Vector Network Analysis Tool
.RE
.SH SEE ALSO
\fI
wxGUI
\fR
.SH SOURCE CODE
.PP
Available at:
wxGUI Components source code
(history)
.PP
Latest change: Tuesday Dec 17 20:17:20 2024 in commit: d962e90c026708a4815ea2b9f46c0e84c17de22d
.PP
Main index |
Wxgui index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2025
GRASS Development Team,
GRASS GIS 8.4.1 Reference Manual
