.TH wxguiintro 1 "" "GRASS 8.4.1" "GRASS GIS User's Manual"
.SH wxGUI in GRASS GIS
.SS Introduction to the GRASS GIS Graphical User Interface
.SS Overview
The wxGUI (wxPython\-based Graphical User Interface) is the primary user
interface for GRASS GIS. Designed for efficiency and ease of use, the
wxGUI provides an intuitive way to interact with spatial data and the
powerful tools available in GRASS GIS.
The GUI supports the visualisation of spatial data, the execution of
geoprocessing tasks or the management of complex workflows and offers a
comprehensive set of tools.
.SS Features
The wxGUI is designed to cater to both novice and advanced users with
the following features:
.RS 4n
.IP \(bu 4n
A clean and customizable layout for efficient workspace management.
.IP \(bu 4n
Integrated support for both raster and vector data operations.
.IP \(bu 4n
Drag\-and\-drop capabilities for quick layer addition and arrangement.
.IP \(bu 4n
Support for live previews of data and processing results.
.IP \(bu 4n
Direct access to GRASS GIS modules, complete with user\-friendly
dialog windows.
.IP \(bu 4n
Advanced debugging and scripting capabilities for developers and
power users.
.RE
.SS Getting Started
To launch the wxGUI, simply start GRASS GIS. Upon startup, the wxGUI will
load, providing access to its various components.
The wxGUI usage is explained in greater detail here.
New GRASS GIS users can explore the integrated help system or visit the
GRASS GIS documentation
for tutorials and guides.
.SS Key Components
The wxGUI is composed of several modules and features:
.RS 4n
.IP \(bu 4n
Map Display: Visualize raster, vector, and 3D data
layers in an interactive map viewer.
.IP \(bu 4n
Layer Manager: Organize and control the visibility,
styling, and properties of your data layers.
.IP \(bu 4n
Data Catalog: Explore and manage GRASS GIS mapsets
and spatial data with ease.
.IP \(bu 4n
Geoprocessing Tools: Access a wide range of geospatial
analysis and modeling tools through an easy\-to\-use interface.
.IP \(bu 4n
Command Console: Run GRASS GIS commands directly,
with syntax highlighting and autocompletion support.
.IP \(bu 4n
3D View: Analyze and visualize 3D landscapes
using NVIZ.
.RE
The wxGUI components are explained in greater detail
here.
.SS See also
.RS 4n
.IP \(bu 4n
Introduction to raster data processing
.IP \(bu 4n
Introduction to 3D raster data (voxel) processing
.IP \(bu 4n
Introduction to image processing
.IP \(bu 4n
Introduction into temporal data processing
.IP \(bu 4n
Introduction to database management
.IP \(bu 4n
Projections and spatial transformations
.RE
.SH SOURCE CODE
.PP
Available at:
wxGUI in GRASS GIS source code
(history)
.PP
Latest change: Thursday Jan 16 15:18:17 2025 in commit: 21cb521140696521c098abcc2a706f4a6c45051e
.PP
Main index |
Wxgui index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2025
GRASS Development Team,
GRASS GIS 8.4.1 Reference Manual
