.TH wxGUI.toolboxes 1 "" "GRASS 8.4.1" "GRASS GIS User's Manual"
.SH wxGUI Toolboxes
.SH KEYWORDS
general, GUI
.SH DESCRIPTION
The \fBToolboxes\fR is a way to customize items in \fIwxGUI\fR
menu. Toolboxes enable to:
.RS 4n
.IP \(bu 4n
hide unused menu items in menu (e.g. Imagery, Database) or submenu (e.g. Wildfire modeling)
.IP \(bu 4n
change order of menu items and subitems
.IP \(bu 4n
add new menu items (e.g. Temporal)
.IP \(bu 4n
add addons modules
.IP \(bu 4n
add your own modules
.RE
.PP
Toolboxes are configured through two XML files (\fCmain_menu.xml\fR and
\fCtoolboxes.xml\fR) located in your user home
GRASS directory, subdirectory \fCtoolboxes\fR
(\fC$HOME/.grass8/toolboxes/\fR on UNIX).
Currently, there is no GUI front\-end for toolboxes,
however only simple editing of text files is needed.
.SS Brief description of file \fCmain_menu.xml\fR
.PP
This file represents the main menu (File, Settings, Raster, ...).
By modifying this file you show and hide menu items which are
represented by \fCsubtoolbox\fR tag.
.PP
Tag \fCuser\-toolboxes\-list\fR is interpreted as a menu containing a list of all user\-defined toolboxes. If not needed it can be removed.
.PP
Following lines can be copied to \fC.grass8/toolboxes/main_menu.xml\fR
and by removing, adding or reordering lines users can change the main menu items. See further examples.
.br
.nf
\fC
<?xml version=\(dq1.0\(dq encoding=\(dqUTF\-8\(dq?>
<toolbox name=\(dqMyMainMenu\(dq>
  <label>Default GRASS GIS main menu bar</label>
  <items>
    <subtoolbox name=\(dqFile\(dq/>
    <subtoolbox name=\(dqSettings\(dq/>
    <subtoolbox name=\(dqRaster\(dq/>
    <subtoolbox name=\(dqVector\(dq/>
    <subtoolbox name=\(dqImagery\(dq/>
    <subtoolbox name=\(dqVolumes\(dq/>
    <subtoolbox name=\(dqDatabase\(dq/>
    <user\-toolboxes\-list />
    <subtoolbox name=\(dqHelp\(dq/>
  </items>
</toolbox>
\fR
.fi
.SS Brief description of file \fCtoolboxes.xml\fR
.PP
This file contains structure and description of individual toolboxes.
Note that both \fIRaster\fR and e.g. \fIQuery raster maps\fR
are individual toolboxes although one contains the other.
Tag \fCtoolbox\fR contains \fCsubtoolbox\fR tags
which are defined later in the file. These nested toolboxes are linked
through \fCname\fR attribute.
.PP
Apart from \fCsubtoolbox\fR tag, tag \fCtoolbox\fR can contain individual items (modules)
and separators (for visual separation in the menu tree).
.br
.nf
\fC
<?xml version=\(dq1.0\(dq encoding=\(dqUTF\-8\(dq?>
<toolboxes>
  <toolbox name=\(dqRaster\(dq>
    <label>&amp;Raster</label>
    <items>
      <subtoolbox name=\(dqDevelopRasterMap\(dq/>
      <subtoolbox name=\(dqManageRasterColors\(dq/>
      <subtoolbox name=\(dqQueryRasterMaps\(dq/>
      <subtoolbox name=\(dqRasterMapTypeConversions\(dq/>
      <separator/>
      <module\-item name=\(dqr.buffer\(dq>
        <label>Buffer rasters</label>
      </module\-item>
      ...
      ...
  <toolbox name=\(dqQueryRasterMaps\(dq>
    <label>Query raster maps</label>
    <items>
      <module\-item name=\(dqr.what\(dq>
        <label>Query values by coordinates</label>
      </module\-item>
      <module\-item name=\(dqr.what.color\(dq>
        <label>Query colors by value</label>
      </module\-item>
    </items>
  </toolbox>
\fR
.fi
.PP
To redefine a toolbox (or use it as a template),
copy specific part of file \fCgrass7/gui/wxpython/xml/toolboxes.xml\fR
from GRASS installation to a new file in user home
(\fC.grass8/toolboxes/toolboxes.xml\fR) and edit it.
Rename this new toolbox.
.SH EXAMPLES
.SS Hiding menu items
.PP
If we are for example working only with raster data,
we can hide menu items \fIVector\fR and \fIDatabase\fR.
The file \fCmain_menu.xml\fR then contains the following lines
where we omitted the two toolboxes:
.br
.nf
\fC
<?xml version=\(dq1.0\(dq encoding=\(dqUTF\-8\(dq?>
<toolbox name=\(dqCustomizedMainMenu\(dq>
  <label>Default GRASS GIS main menu bar</label>
  <items>
    <subtoolbox name=\(dqFile\(dq/>
    <subtoolbox name=\(dqSettings\(dq/>
    <subtoolbox name=\(dqRaster\(dq/>
    <subtoolbox name=\(dqImagery\(dq/>
    <subtoolbox name=\(dqVolumes\(dq/>
    <user\-toolboxes\-list />
    <subtoolbox name=\(dqHelp\(dq/>
  </items>
</toolbox>
\fR
.fi
.SS Creating custom toolbox
.PP
In this example we create a new toolbox \fIFavorites\fR containing
existing GRASS module and toolbox, custom module
created by the user and addon module.
The \fCtoolboxes.xml\fR file contains following lines:
.br
.nf
\fC
<?xml version=\(dq1.0\(dq encoding=\(dqUTF\-8\(dq?>
<toolboxes>
  <toolbox name=\(dqMyFavorites\(dq>
    <label>&amp;Favorites</label>
    <items>
      <module\-item name=\(dqg.region\(dq>
        <label>Set region</label>
      </module\-item>
      <module\-item name=\(dqr.mask\(dq>
        <label>Mask</label>
      </module\-item>
      <separator/>
      <module\-item name=\(dqm.myown\(dq>
        <label>Do my own stuff</label>
      </module\-item>
      <module\-item name=\(dqi.histo.match\(dq>
        <label>Calculate histogram matching</label>
      </module\-item>
      <subtoolbox name=\(dqRasterReportsAndStatistics\(dq/>
    </items>
  </toolbox>
</toolboxes>
\fR
.fi
.PP
Optionally, we can add this toolbox to the main menu items.
The \fCmain_menu.xml\fR file contains following lines:
.br
.nf
\fC
<?xml version=\(dq1.0\(dq encoding=\(dqUTF\-8\(dq?>
<toolbox name=\(dqCustomizedMainMenu\(dq>
  <label>Default GRASS GIS main menu bar</label>
  <items>
    <subtoolbox name=\(dqFile\(dq/>
    <subtoolbox name=\(dqSettings\(dq/>
    <subtoolbox name=\(dqRaster\(dq/>
    <subtoolbox name=\(dqVector\(dq/>
    <subtoolbox name=\(dqImagery\(dq/>
    <subtoolbox name=\(dqVolumes\(dq/>
    <subtoolbox name=\(dqDatabase\(dq/>
    <user\-toolboxes\-list />
    <subtoolbox name=\(dqFavorites\(dq/>
    <subtoolbox name=\(dqHelp\(dq/>
  </items>
</toolbox>
\fR
.fi
.PP
If we have \fCuser\-toolboxes\-list\fR tag in the \fCmain_menu.xml\fR file,
our custom toolbox will be listed in the automatically added \fIToolboxes\fR main menu item. The screenshot shows the resulting menu:
.br
.br
.br
.SH NOTES
.PP
After the first start of wxGUI with custom toolboxes,
\fC.grass/toolboxes\fR directory will contain file
\fCmenudata.xml\fR which is auto\-generated and should not be edited.
.SH SEE ALSO
\fI
wxGUI,
wxGUI components
\fR
.SH AUTHORS
Anna Petrasova, OSGeoREL, Faculty of Civil Engineering, Czech Technical University in Prague
.br
Vaclav Petras, OSGeoREL, Faculty of Civil Engineering, Czech Technical University in Prague
.SH SOURCE CODE
.PP
Available at:
wxGUI Toolboxes source code
(history)
.PP
Latest change: Tuesday Dec 17 20:17:20 2024 in commit: d962e90c026708a4815ea2b9f46c0e84c17de22d
.PP
Main index |
Wxgui index |
Topics index |
Keywords index |
Graphical index |
Full index
.PP
© 2003\-2025
GRASS Development Team,
GRASS GIS 8.4.1 Reference Manual
